// games.js
export const games = [
	{
		id: 1,
		name: "Assassin's Creed 3",
		price: 40.0,
		image: "img/index1.jpeg",
		description: "Assassin's Creed 3 description...",
		details: "Assassin's Creed 3...",
		quantity: 1,
		type: "Games",
	},
	{
		id: 2,
		name: "The Witcher 3",
		price: 22.0,
		image: "img/index2.jpg",
		description: "The Witcher 3 description...",
		details: "The Witcher 3...",
		quantity: 1,
		type: "Games",
	},
	{
		id: 3,
		name: "Grand Theft Auto V",
		price: 41.0,
		image: "img/index3.jpg",
		description: "Grand Theft Auto V description...",
		details: "Grand Theft Auto V details info ...",
		quantity: 1,
		type: "Games",
	},
	{
		id: 4,
		name: "The Witcher 3: Blood & Wine",
		price: 50.0,
		image: "img/index5.avif",
		description: "The Witcher 3: Blood & Wine description...",
		details: "The Witcher 3: Blood & Wine details info...",
		quantity: 1,
		type: "DLCs",
		baseGameId: 2,
	},
	{
		id: 5,
		name: "Forza Horizon 5",
		price: 50.0,
		image: "img/index4.jpeg",
		description: "Forza Horizon 5 description...",
		details: "Forza Horizon 5 details info...",
		quantity: 1,
		type: "Games",
	},
]
